spring:
  mvc:
    view:
      prefix: "/WEB-INF/view/"
      suffix: ".jsp"
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 80
  context-path: "/spring-boot/"
logging:
  level:
    root: error



